[package]
name = "tobira"
version = "0.1.0"
authors = [
    "The Opencast project",
    "Lukas Kalbertodt <kalbertodt@elan-ev.de>",
    "Julian Kniephoff <kniephoff@elan-ev.de>",
    "Lars Kiesow <lkiesow@uos.de>",
]
edition = "2021"
publish = false
description = "Backend of the Tobira video portal for Opencast"


[features]
embed-in-debug = ["reinda/debug-is-prod"]


[dependencies]
anyhow = "1"
base64 = "0.13"
bstr = "0.2.17"
bunt = "0.2.4"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["serde", "std"] }
confique = { version = "0.1.1", default-features = false, features = ["toml"] }
cookie = "0.15"
deadpool = { version = "0.9.0", default-features = false, features = ["managed", "rt_tokio_1"] }
deadpool-postgres = { version = "0.10", default-features = false, features = ["rt_tokio_1"] }
elliptic-curve = { version = "0.11.1", features = ["jwk", "sec1"] }
futures = { version = "0.3.1", default-features = false, features = ["std"] }
hostname = "0.3"
hyper = { version = "0.14", features = ["client", "http1", "http2"] }
hyper-rustls = "0.22"
hyperlocal = { version = "0.8", default-features = false, features = ["server"] }
juniper = { version = "0.15.7", default-features = false, features = ["chrono", "schema-language"] }
juniper_hyper = "0.8.0"
log = { version = "0.4", features = ["serde", "std"] }
mime_guess = { version = "2", default-features = false }
once_cell = "1.5"
p256 = { git = "https://github.com/RustCrypto/elliptic-curves.git", features = ["jwk"] }
paste = "1"
pem = "1"
pin-utils = "0.1.0"
postgres-types = { version = "0.2.2", features = ["derive", "array-impls"] }
rand = "0.8.4"
reinda = "0.2"
ring = "0.16"
secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
static_assertions = "1"
structopt = "0.3"
tap = "1"
termcolor = "1.1.1"
time = "0.2.27"
tokio = { version = "1.0", features = ["fs", "rt-multi-thread", "macros", "time"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
toml = "0.5"





# Codegen options

[profile.release]
debug = 1
codegen-units = 1
lto = "thin"

[profile.release.package."*"]
debug = false
