# Configuration for development environments: unless you are a Tobira
# developer, you are not interested in this file.

[general]
site_title = "Tobira Videoportal"

[db]
password = "tobira"

[log]
level = "trace"

[auth]
proxy.enabled = true

[sync]
host = "localhost:8080"
use_insecure_connection = true
user = "admin"
password = "opencast"
preferred_harvest_size = 3

[theme]
logo.large.path = "logo-large.svg"
logo.large.resolution = [643, 217]
logo.small.path = "logo-small.svg"
logo.small.resolution = [102, 115]
