# Configuration for devevelopment environments: unless you are a Tobira
# developer, you are not intersted in this file.

[db]
user = "tobira"
password = "tobira"
host = "127.0.0.1"

[assets]
logo.large = "logo-large.svg"
logo.small = "logo-small.svg"
