version: '2'

services:
  nginx:
    container_name: tobira-login-proxy-dummy
    image: nginx
    network_mode: "host"
    ports:
      - "3090:3090"
    volumes:
      - ${PWD}/login-proxy-nginx.conf:/etc/nginx/conf.d/default.conf

