---

- hosts: all
  roles:
    - cloudalchemy.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: 'tobira'
        metrics_path: '/~metrics'
        scrape_interval: 10s
        scrape_timeout: 2s
        static_configs:
          - targets:
            - tobira.opencast.org
