[db]
database = "tobira-{{ id }}"
user = "tobira-{{ id }}"
password = "tobira-{{ id }}"
host = "127.0.0.1"

[http]
unix_socket = "/opt/tobira/{{ id }}/socket/tobira.sock"
unix_socket_permissions = 0o777

[log]
file = "/var/log/tobira/{{ id }}.log"

[opencast]
host = "develop.opencast.org"
sync_user = "admin"
sync_password = "opencast"

[theme]
logo.large = "/opt/tobira/{{ id }}/logo-large.svg"
logo.small = "/opt/tobira/{{ id }}/logo-small.svg"
