[general]
site_title.en = "Tobira Test Deployment"

[db]
database = "tobira-{{ id }}"
user = "tobira-{{ id }}"
password = "tobira-{{ id }}"

[http]
unix_socket = "/opt/tobira/{{ id }}/socket/tobira.sock"
unix_socket_permissions = 0o777

[auth]
mode = "login-proxy"
login_page.note.en = 'Dummy users: "augustus", "sabine" and "admin". Password for all: "tobira".'
login_page.note.de = 'Testnutzer: "augustus", "sabine" und "admin". Passwort für alle: "tobira".'

[auth.jwt]
signing_algorithm = "ES256"
# This is currently not created by scripts, but is expected to be generated there manually.
secret_key = "/opt/tobira/secret-jwt-key.pem"
expiration_time = "10min"

[log]
file = "/var/log/tobira/{{ id }}.log"

[sync]
host = "oc.tobira.ethz.ch"
user = "admin"
password = "{{ opencast_admin_password }}"
poll_period = "1min"

[theme]
logo.large.path = "/opt/tobira/{{ id }}/logo-large.svg"
logo.large.resolution = [643, 217]
logo.small.path = "/opt/tobira/{{ id }}/logo-small.svg"
logo.small.resolution = [102, 115]
