[general]
site_title = "Tobira Test Deployment"

[db]
database = "tobira-{{ id }}"
user = "tobira-{{ id }}"
password = "tobira-{{ id }}"

[http]
unix_socket = "/opt/tobira/{{ id }}/socket/tobira.sock"
unix_socket_permissions = 0o777

[log]
file = "/var/log/tobira/{{ id }}.log"

[sync]
host = "tobira.ethz.ch"
user = "admin"
password = "{{ opencast_admin_password }}"

[theme]
logo.large.path = "/opt/tobira/{{ id }}/logo-large.svg"
logo.large.resolution = [643, 217]
logo.small.path = "/opt/tobira/{{ id }}/logo-small.svg"
logo.small.resolution = [102, 115]
