[db]
database = "tobira-{{ id }}"
user = "tobira-{{ id }}"
password = "tobira-{{ id }}"

[http]
unix_socket = "/opt/tobira/{{ id }}/socket/tobira.sock"
unix_socket_permissions = 0o777

[log]
file = "/var/log/tobira/{{ id }}.log"

[sync]
host = "develop.opencast.org"
user = "admin"
password = "opencast"

[theme]
logo.large = "/opt/tobira/{{ id }}/logo-large.svg"
logo.small = "/opt/tobira/{{ id }}/logo-small.svg"
