version: '2'

services:
  # A reverse proxy in front of Tobira that handles authentication via the login
  # handler.
  tobira-auth-proxy:
    image: nginx
    network_mode: "host"
    volumes:
      - ./tobira-auth-proxy-nginx.conf:/etc/nginx/conf.d/default.conf

  # A simple webserver handling login requests with some dummy users.
  tobira-login-handler:
    image: python:3
    network_mode: "host"
    volumes:
      - ./login-handler.py:/usr/bin/login-handler.py
    command: python -u /usr/bin/login-handler.py

  # A reverse proxy in front of Opencast that just adds some CORS headers
  # (required for the Tobira uploader, for example).
  opencast-cors-proxy:
    image: nginx
    network_mode: "host"
    volumes:
      - ./opencast-cors-proxy-nginx.conf:/etc/nginx/conf.d/default.conf

  # A PostgreSQL database for Tobira.
  tobira-dev-database:
    image: docker.io/library/postgres:10
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - tobira-dev-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tobira
      - POSTGRES_USER=tobira
      - POSTGRES_DB=tobira

  # A MeiliSearch for Tobira.
  tobira-meilisearch:
    image: getmeili/meilisearch:v0.27.2
    restart: unless-stopped
    ports:
      - 127.0.0.1:7700:7700
    volumes:
      - tobira-dev-meili:/data.ms
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=tobira


volumes:
  tobira-dev-postgres:
  tobira-dev-meili:
