version: '2'

services:
  meili:
    image: getmeili/meilisearch:v0.27.2
    restart: unless-stopped
    ports:
      - 127.0.0.1:7700:7700
    volumes:
      - tobira-dev-meili:/data.ms
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=tobira

volumes:
  tobira-dev-meili:
