version: '2'

services:
  nginx:
    container_name: opencast-cors-proxy
    image: nginx
    network_mode: "host"
    ports:
      - "8081:8081"
    volumes:
      - ./cors-nginx.conf:/etc/nginx/conf.d/default.conf

