---

- hosts: all

  vars:
    # will usually be overwritten by --extra-vars='deployid=<id>'
    id: "{{ deployid }}"

  tasks:

    - name: stop and disable tobira
      become: true
      systemd:
        name: '{{ item }}-{{ id }}'
        state: stopped
        enabled: false
      ignore_errors: true
      with_items:
        - tobira
        - tobiraworker
        - tobiraauth

    - name: Clear search index
      become: true
      become_user: tobira
      ignore_errors: true
      command:
        cmd: /opt/tobira/{{ id }}/tobira search-index clear --yes-absolutely-clear-index
        chdir: /opt/tobira/{{ id }}/

    - name: remove deployed files and folders
      become: true
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - /opt/tobira/{{ id }}
        - /etc/systemd/system/tobira-{{ id }}.service
        - /etc/systemd/system/tobiraworker-{{ id }}.service
        - /etc/systemd/system/tobiraauth-{{ id }}.service
        - /etc/nginx/conf.d/tobira-{{ id }}.conf
        - /var/log/tobira/{{ id }}-serve.log
        - /var/log/tobira/{{ id }}-cli.log
        - /var/log/tobira/{{ id }}-worker.log
      notify: reload nginx

    - name: force systemd to reread configs
      become: true
      systemd:
        daemon_reload: yes

    - name: reset failed units
      become: true
      command:
        cmd: systemctl reset-failed

    - name: drop database
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: tobira-{{ id }}
        state: absent

    - name: drop tobira postgres user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: tobira-{{ id }}
        state: absent

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded
