name: Build & test

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    # Backend cache: this cache stores cargo caches and compiled dependencies to
    # speed up compiling the backend. We use a key consisting of the lock file,
    # the compiler version and the global compiler flags. If either of the
    # latter two change, everything is recompiled anyway. The lockfile is used,
    # too, to avoid caching dependencies that have been removed already. Also
    # compare: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - name: Prepare backend cache key
      run: |
        cp backend/Cargo.lock cache-fingerprint
        echo "$RUSTFLAGS $(rustc -V)" >> cache-fingerprint
    - name: Restore backend cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          backend/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('cache-fingerprint') }}

    # Frontend cache: only the NPM folder is cached, not the node_modules, as
    # recommended here: https://github.com/actions/cache/blob/main/examples.md#node---npm
    - name: Restore NPM cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

    # Figure out build mode
    - name: Determine build mode
      id: build_mode
      run: |
        if [[ "$GITHUB_REPOSITORY" == "elan-ev/tobira" ]] && [ "$GITHUB_REF" == "refs/heads/master" ]; then
          echo "::set-output name=cargo::--release"
          echo "::set-output name=targetdir::target/release"
          echo "::set-output name=webpack::production"
        else
          echo "::set-output name=cargo::--features=embed-in-debug"
          echo "::set-output name=targetdir::target/debug"
          echo "::set-output name=webpack::development"
        fi

    # The actual building and testing!
    - name: Installing frontend dependencies (npm ci)
      working-directory: frontend
      run: npm ci
    - name: Generate GraphQL query types
      working-directory: frontend
      run: npx relay-compiler
    - name: Typecheck frontend
      working-directory: frontend
      run: tsc
    - name: Lint frontend
      working-directory: frontend
      run: npx eslint --max-warnings 0 .
    - name: Build frontend
      working-directory: frontend
      run: npx webpack --mode=${{ steps.build_mode.outputs.webpack }}

    - name: Build backend
      working-directory: backend
      run: cargo build
    - name: Test backend
      working-directory: backend
      run: cargo test
    - name: Generate documenation for backend
      working-directory: backend
      run: cargo doc --no-deps
    - name: Make sure `schema.graphql` is up to date
      working-directory: backend
      run: cargo run --bin export-schema | diff -u --color=always - ../frontend/src/schema.graphql

    # Prepare binary for deployment
    - name: Build server binary for test deployment
      working-directory: backend/server
      run: cargo build ${{ steps.build_mode.outputs.cargo }}

    # Prepare the ID (used in the subdomain) for deployment. This has to be done
    # here because in the `deploy` workflow, we don't have access to the correct
    # `GITHUB_REF` anymore.
    - name: Write deploy ID to file
      run: ./.deployment/deploy-id.sh "$GITHUB_REF" > deploy-id

    # Archive files to be used in the `deploy` workflow
    - name: Move deploy binary
      run: mv backend/${{ steps.build_mode.outputs.targetdir }}/tobira tobira
    - name: Archive deployment files as artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-deployment-files
        path: |
          tobira
          scripts/fixtures.sql
          backend/logo-large.svg
          backend/logo-small.svg
          deploy-id
          .deployment/templates/config.toml
