name: Remove deployment

on:
  delete:
  pull_request_target:
    types: [ closed ]

jobs:
  main:
    if: github.repository_owner == 'elan-ev'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: prepare deploy key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        install -dm 700 ~/.ssh/
        echo "${DEPLOY_KEY}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan tobira.opencast.org >> ~/.ssh/known_hosts

    - name: install ansible postgres extensions
      run: ansible-galaxy collection install community.postgresql

    - name: Write deploy ID (for branch) to file
      run: ./.deployment/deploy-id.sh "${{ github.event.ref }}" > deploy-id
      if: github.event_name == 'delete'

    - name: Write deploy ID (for PR) to file
      run: ./.deployment/deploy-id.sh "refs/pull/${{ github.event.pull_request.number }}/merge" > deploy-id
      if: github.event_name != 'delete'

    - name: remove deployment
      working-directory: .deployment
      run: >
        ansible-playbook
        --private-key=~/.ssh/id_ed25519
        --extra-vars="deployid='$(cat ../deploy-id)'"
        -u github
        remove-deployment.yml
